name: gpth
description: 'Tool to help you with exporting stuff from Google Photos'
version: 4.0.5
homepage: 'https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper'
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  mime: ^2.0.0
  collection: ^1.18.0
  convert: ^3.1.1
  fuzzysearch: ^0.1.3
  crypto: ^3.0.3
  console_bars: ^1.2.0
  intl: ^0.20.2
  file_picker_desktop: ^1.2.0
  exif_reader: ^3.16.1
  image: ^4.5.4
  emoji_regex: ^0.0.5

  #  archive:
  #    git:
  #      url: https://github.com/TheLastGimbus/archive.git
  #      ref: fix-windoza-extract-errors
  proper_filesize: ^1.0.2
  unorm_dart: ^0.3.0
  win32: ^5.13.0
  ffi: ^2.1.4
  coordinate_converter: ^1.2.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
